development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:db0f77facda5c10e8bf48069fea3ae1b@pike.redistogo.com:11595/
  channel_prefix: SoulFunk_production
